<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DELFOS.JWT.SSO.MODELS\DELFOS.JWT.SSO.MODELS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\en-us\Controllers\" />
    <Folder Include="Areas\en-us\Data\" />
    <Folder Include="Areas\en-us\Models\" />
    <Folder Include="Areas\es-sp\Controllers\" />
    <Folder Include="Areas\es-sp\Data\" />
    <Folder Include="Areas\es-sp\Models\" />
    <Folder Include="Areas\pt-br\Controllers\" />
    <Folder Include="Areas\pt-br\Data\" />
    <Folder Include="Areas\pt-br\Models\" />
  </ItemGroup>

</Project>
