// <auto-generated />
using System;
using DELFOS.JWT.SSO.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DELFOS.JWT.SSO.API.Data.Migrations
{
    [DbContext(typeof(DELFOS_JWT_SSO_Context))]
    [Migration("20221107183300_CriacaoInicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.AppPortifolio", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AppId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AppId"), 1L, 1);

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ApplicationName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.HasKey("AppId")
                        .HasName("AppPortifolio_PK");

                    b.ToTable("AppPortifolio");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.BillModel", b =>
                {
                    b.Property<long>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BillId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BillId"), 1L, 1);

                    b.Property<string>("Tipo")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Tipo")
                        .HasComment("Tipo do meio de pagamento:\r\n\r\n- Pix (PIX)\r\n- CC (Cartão de Crédito)\r\n- DEB (Cartão de Débito)\r\n- BLT (Boleto)");

                    b.Property<string>("UrlAPI")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UrlAPI");

                    b.HasKey("BillId")
                        .HasName("BillModel_PK");

                    b.ToTable("Tb_BillModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.CityModel", b =>
                {
                    b.Property<long>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CityId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CityId"), 1L, 1);

                    b.Property<string>("IBGE")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("IBGE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name")
                        .HasComment("	");

                    b.Property<long>("StateModelStateId")
                        .HasColumnType("bigint")
                        .HasColumnName("StateModel_StateId");

                    b.HasKey("CityId")
                        .HasName("CityModel_PK");

                    b.HasIndex(new[] { "StateModelStateId" }, "CityModel__IDX")
                        .IsUnique();

                    b.ToTable("Tb_CityModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.CountryModel", b =>
                {
                    b.Property<long>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CountryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CountryId"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Fone");

                    b.Property<string>("ISO")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ISO");

                    b.Property<string>("ISO3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("ISO3");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("NomeFormal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NomeFormal");

                    b.HasKey("CountryId")
                        .HasName("CountryModel_PK");

                    b.ToTable("Tb_CountryModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.EnrollmentModel", b =>
                {
                    b.Property<long>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EnrollmentId")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnrollmentId"), 1L, 1);

                    b.Property<long>("UserModelUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserModel_UserId")
                        .HasColumnOrder(2);

                    b.Property<long>("AppPortifolioAppId")
                        .HasColumnType("bigint")
                        .HasColumnName("AppPortifolio_AppId");

                    b.Property<long>("SignatureModelSignatureId")
                        .HasColumnType("bigint")
                        .HasColumnName("SignatureModel_SignatureId");

                    b.HasKey("EnrollmentId", "UserModelUserId")
                        .HasName("EnrollmentModel_PK");

                    b.HasIndex("UserModelUserId");

                    b.HasIndex(new[] { "AppPortifolioAppId" }, "EnrollmentModel__IDX")
                        .IsUnique();

                    b.HasIndex(new[] { "SignatureModelSignatureId" }, "EnrollmentModel__IDXv1")
                        .IsUnique();

                    b.ToTable("Tb_EnrollmentModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.OrganizationModel", b =>
                {
                    b.Property<long>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OrganizationId")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrganizationId"), 1L, 1);

                    b.Property<string>("CNPJ")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CNPJ")
                        .HasColumnOrder(2);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Address");

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("CV")
                        .HasComment("código de verificação do cartão de crédito");

                    b.Property<long>("CityModelCityId")
                        .HasColumnType("bigint")
                        .HasColumnName("CityModel_CityId");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("CreditCardNumber");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("District");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EmailContact");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("NumberAddr")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("NumberAddr");

                    b.Property<string>("Razao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Razao")
                        .HasComment("																																								");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("ZipCode");

                    b.HasKey("OrganizationId", "CNPJ")
                        .HasName("OrganizationModel_PK");

                    b.HasIndex(new[] { "CityModelCityId" }, "OrganizationModel__IDX")
                        .IsUnique();

                    b.ToTable("Tb_OrganizationModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.RoleModel", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleId")
                        .HasName("RoleModel_PK");

                    b.ToTable("Tb_RoleModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.SignatureModel", b =>
                {
                    b.Property<long>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SignatureId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SignatureId"), 1L, 1);

                    b.Property<long>("AppId")
                        .HasColumnType("bigint")
                        .HasColumnName("AppId");

                    b.Property<long>("BillModelBillId")
                        .HasColumnType("bigint")
                        .HasColumnName("BillModel_BillId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("KeySignature")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("KeySignature");

                    b.Property<string>("OrganizationModelCnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("OrganizationModel_CNPJ");

                    b.Property<long>("OrganizationModelOrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("OrganizationModel_OrganizationId");

                    b.HasKey("SignatureId")
                        .HasName("SignatureModel_PK");

                    b.HasIndex(new[] { "BillModelBillId" }, "SignatureModel__IDX")
                        .IsUnique();

                    b.HasIndex(new[] { "OrganizationModelOrganizationId", "OrganizationModelCnpj" }, "SignatureModel__IDXv1")
                        .IsUnique();

                    b.ToTable("Tb_SignatureModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.StateModel", b =>
                {
                    b.Property<long>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("StateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StateId"), 1L, 1);

                    b.Property<long>("CountryModelCountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("CountryModel_CountryId");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DDD");

                    b.Property<string>("IBGECode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("IBGECode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("UF");

                    b.HasKey("StateId")
                        .HasName("StateModel_PK");

                    b.HasIndex("CountryModelCountryId")
                        .IsUnique();

                    b.ToTable("Tb_StateModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.UserLogin", b =>
                {
                    b.Property<long>("UserLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserLoginId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserLoginId"), 1L, 1);

                    b.Property<bool?>("AuthenticateResult")
                        .HasColumnType("bit")
                        .HasColumnName("AuthenticateResult");

                    b.Property<DateTime?>("CreateLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("CreateLogin");

                    b.Property<string>("LOG")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOG");

                    b.Property<DateTime?>("LogTime")
                        .HasColumnType("datetime")
                        .HasColumnName("LogTime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Password");

                    b.Property<long?>("UserModelUserId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("UserModel_UserId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserName");

                    b.HasKey("UserLoginId")
                        .HasName("UserLogin_PK");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("Tb_UserLogin");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.UserModel", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("GivenName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Role");

                    b.Property<long?>("RoleModelRoleId")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("RoleModel_RoleId");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RoleName");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Surname");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("UserName");

                    b.HasKey("UserId")
                        .HasName("UserModel_PK");

                    b.HasIndex("RoleModelRoleId");

                    b.ToTable("Tb_UserModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.CityModel", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.StateModel", "StateModelState")
                        .WithOne("TbCityModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.CityModel", "StateModelStateId")
                        .IsRequired()
                        .HasConstraintName("CityModel_StateModel_FK");

                    b.Navigation("StateModelState");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.EnrollmentModel", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.AppPortifolio", "AppPortifolioApp")
                        .WithOne("TbEnrollmentModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.EnrollmentModel", "AppPortifolioAppId")
                        .IsRequired()
                        .HasConstraintName("EnrollmentModel_AppPortifolio_FK");

                    b.HasOne("DELFOS.JWT.SSO.MODELS.SignatureModel", "SignatureModelSignature")
                        .WithOne("TbEnrollmentModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.EnrollmentModel", "SignatureModelSignatureId")
                        .IsRequired()
                        .HasConstraintName("EnrollmentModel_SignatureModel_FK");

                    b.HasOne("DELFOS.JWT.SSO.MODELS.UserModel", "UserModelUser")
                        .WithMany("TbEnrollmentModels")
                        .HasForeignKey("UserModelUserId")
                        .IsRequired()
                        .HasConstraintName("EnrollmentModel_UserModel_FK");

                    b.Navigation("AppPortifolioApp");

                    b.Navigation("SignatureModelSignature");

                    b.Navigation("UserModelUser");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.OrganizationModel", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.CityModel", "CityModelCity")
                        .WithOne("TbOrganizationModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.OrganizationModel", "CityModelCityId")
                        .IsRequired()
                        .HasConstraintName("OrganizationModel_CityModel_FK");

                    b.Navigation("CityModelCity");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.SignatureModel", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.BillModel", "BillModelBill")
                        .WithOne("TbSignatureModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.SignatureModel", "BillModelBillId")
                        .IsRequired()
                        .HasConstraintName("SignatureModel_BillModel_FK");

                    b.HasOne("DELFOS.JWT.SSO.MODELS.OrganizationModel", "OrganizationModel")
                        .WithOne("TbSignatureModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.SignatureModel", "OrganizationModelOrganizationId", "OrganizationModelCnpj")
                        .IsRequired()
                        .HasConstraintName("SignatureModel_OrganizationModel_FK");

                    b.Navigation("BillModelBill");

                    b.Navigation("OrganizationModel");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.StateModel", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.CountryModel", "CountryModelCountry")
                        .WithOne("TbStateModel")
                        .HasForeignKey("DELFOS.JWT.SSO.MODELS.StateModel", "CountryModelCountryId")
                        .IsRequired()
                        .HasConstraintName("StateModel_CountryModel_FK");

                    b.Navigation("CountryModelCountry");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.UserLogin", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.UserModel", "UserModelUser")
                        .WithMany("TbUserLogins")
                        .HasForeignKey("UserModelUserId")
                        .IsRequired()
                        .HasConstraintName("UserLogin_UserModel_FK");

                    b.Navigation("UserModelUser");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.UserModel", b =>
                {
                    b.HasOne("DELFOS.JWT.SSO.MODELS.RoleModel", "RoleModelRole")
                        .WithMany("TbUserModels")
                        .HasForeignKey("RoleModelRoleId")
                        .IsRequired()
                        .HasConstraintName("UserModel_RoleModel_FK");

                    b.Navigation("RoleModelRole");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.AppPortifolio", b =>
                {
                    b.Navigation("TbEnrollmentModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.BillModel", b =>
                {
                    b.Navigation("TbSignatureModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.CityModel", b =>
                {
                    b.Navigation("TbOrganizationModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.CountryModel", b =>
                {
                    b.Navigation("TbStateModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.OrganizationModel", b =>
                {
                    b.Navigation("TbSignatureModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.RoleModel", b =>
                {
                    b.Navigation("TbUserModels");
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.SignatureModel", b =>
                {
                    b.Navigation("TbEnrollmentModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.StateModel", b =>
                {
                    b.Navigation("TbCityModel")
                        .IsRequired();
                });

            modelBuilder.Entity("DELFOS.JWT.SSO.MODELS.UserModel", b =>
                {
                    b.Navigation("TbEnrollmentModels");

                    b.Navigation("TbUserLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
