INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Acre', 'AC', 12, 269, '68')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Alagoas', 'AL', 27, 269, '82')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Amazonas', 'AM', 13, 269, '97,92')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Amapá', 'AP', 16, 269, '96')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Bahia', 'BA', 29, 269, '77,75,73,74,71')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Ceará', 'CE', 23, 269, '88,85')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Distrito Federal', 'DF', 53, 269, '61')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Espírito Santo', 'ES', 32, 269, '28,27')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Goiás', 'GO', 52, 269, '62,64,61')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Maranhão', 'MA', 21, 269, '99,98')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Minas Gerais', 'MG', 31, 269, '34,37,31,33,35,38,32')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Mato Grosso do Sul', 'MS', 50, 269, '67')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Mato Grosso', 'MT', 51, 269, '65,66')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Pará', 'PA', 15, 269, '91,94,93')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Paraíba', 'PB', 25, 269, '83')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Pernambuco', 'PE', 26, 269, '81,87')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Piauí', 'PI', 22, 269, '89,86')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Paraná', 'PR', 41, 269, '43,41,42,44,45,46')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Rio de Janeiro', 'RJ', 33, 269, '24,22,21')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Rio Grande do Norte', 'RN', 24, 269, '84')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Rondônia', 'RO', 11, 269, '69')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Roraima', 'RR', 14, 269, '95')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Rio Grande do Sul', 'RS', 43, 269, '53,54,55,51')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Santa Catarina', 'SC', 42, 269, '47,48,49')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Sergipe', 'SE', 28, 269, '79')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('São Paulo', 'SP', 35, 269, '11,12,13,14,15,16,17,18,19')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Tocantins', 'TO', 17, 269, '63')
INSERT INTO Tb_States ( Name, Uf, IBGECode, CountryId, DDD) VALUES('Exterior', 'EX', 99, NULL, NULL);